apiVersion: v1
kind: Pod 
metadata: 
  name: pods-3 
  labels: 
    app: sample-env-3
spec: 
  containers:
  - name: color-3 
    image: mmumshad/simple-webapp-color 
    ports:
    - containerPort: 8080
    envFrom: 
    - configMapRef:
        name: conf 
        # key: APP_COLOR