apiVersion: apps/v1
kind: DaemonSet 
metadata: 
  name: daemon
  labels: 
    app: nginx-app
spec: 
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata: 
      labels: 
        app: nginx-app
    spec: 
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80